baseURL = 'https://creative-fudge-f9a80d.netlify.app/'
languageCode = 'en-us'
title = 'Babakoviny'
description = "školní noviny"

theme = "hugo-theme-stack"

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"
    [menu.main.params]
        icon = "home"
        newTab = false
[[menu.main]]
    name = "Aktuality"
    url = "/categories/aktuality/"
    weight = 2
    identifier = "aktuality"
    [menu.main.params]
        icon = "messages"
	newTab = false
[[menu.main]]
    name = "Rozhovory"
    url = "/categories/rozhovory/"
    weight = 3
    identifier = "roozhovory"
    [menu.main.params]
        icon = "microphone"
	newTab = false  
[[menu.main]]
    name = "Kultura"
    url = "/categories/kultura/"
    weight = 4
    identifier = "kultura"
    [menu.main.params]
        icon = "forest"
	newTab = false  
[[menu.main]]
    name = "Sport"
    url = "/categories/sport/"
    weight = 5
    identifier = "sport"
    [menu.main.params]
        icon = "football"
	newTab = false      
[[menu.main]]
    name = "O nás"
    url = "/About"
    weight = 20
    identifier = "about"
    [menu.main.params]
        icon = "clock"
        newTab = false
        
[widgets]        
[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10
